services:
  - type: web
    name: fastapi-backend
    rootDir: api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

  - type: web
    name: streamlit-frontend
    rootDir: Streamlit_app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      
      BACKEND_URL: "https://fastapi-backend-cda5.onrender.com"